### ISSUE TITLE
Meaning of warning logs

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/e-skGovCRZ#6]
The DPU logs a lot of warnings about invalid keys. For example, `Invalid key: popis-zmluvy` or `Invalid key: posledna-zmena`. Is this expected?

**Comment by pgo-eea-sk** [comment]
When the extractor was implemented popis-zmluvy and posledna-zmena were not on the first pages I checked, so they are "unknown" for DPU and not included in the result.

**Comment by jindrichmynarz** [comment]
OK, then we can have an enhancement of adding these keys.
